### ISSUE TITLE
Example does not work: ValueError: too many values to unpack

### ISSUE THREAD

**Issue by bafonso** [cdw/TiffCapture#1]
```
for f,img in tiff:
```

ValueError: too many values to unpack

**Comment by cdw** [comment]
Ah, thanks. That was from an earlier iteration. I've corrected the example and, as a bonus, made the package compatible with python3.

**Comment by ljschumacher** [comment]
I'm trying to use this in python3, but I keep getting an error from:
"from tiffcapture import opentiff"
ImportError: cannot import name 'opentiff'

commenting the line seems to have made it work for me
