### ISSUE TITLE
Can you please update the PYPI version?

### ISSUE THREAD

**Issue by Palpatineli** [cdw/TiffCapture#3]
Hello cdw,

I noticed that your nice library is only 0.1.3 on pypi even when  it's listed as 0.1.4. That version was working well with python3 but your current 0.1.5 version does. Would you mind updating your library on PyPI to 0.1.5 too? Thanks!

**Comment by cdw** [comment]
Hi hi,

Huh, odd. It looked updated on the PyPi website and when searching on pip, but on install from pip it   was still the older version. Should be fixed now by moving to hosting the releases on github (steps documented in [release_steps.md](https://github.com/cdw/TiffCapture/blob/master/release_steps.md) for future reference. 

Cheers
